openapi: 3.0.1
info:
  title: mvnApi
  description: API Definition of mvnApi
  version: 1.0.0
servers:
- url: http://localhost:8290/mvnapi
paths:
  /:
    get:
      responses:
        default:
          description: Default response
